#!/usr/bin/env python3
"""Read-only reconciliation of every beat that no method could serve.

Requested by Codex, 2026-09-21: "make a read-only reconciliation table for the eight
denied beats... For each, show its required visual operation and forbidden implication;
what the old, new, and merged binding pools would offer; and whether each condition can
actually be met with supported template controls."

Widened from their 8 to the 11 that failed under EITHER method, because a beat one
method served and the other did not is the more informative case.

CHANGES NOTHING. It does not judge fit. Where a judgement is required — can this
condition actually be met — it prints the condition verbatim and marks it UNRESOLVED,
because that judgement belongs to the user or to a versioned prompt, never to this
script and never to a reading.

    python3 pipeline/reconcile_denied.py > no-drifting/RECONCILE-denied-beats.md
"""
import json, pathlib, re, sys, collections
P = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(P.parent / "match-trial"))
import candidates as C

G = P.parent / "grammar"
POOLS = {"old (pre-rebind)": "/tmp/bindings.pre-full.json",
         "new (full rebind)": "/tmp/bindings.fullrun.json",
         "merged (live)": str(G / "bindings.json")}

def rag_ledger():
    md = (P.parent / "handoff" / "inbox" /
          "022-from-codex-second-brain-and-beat-review.md").read_text()
    out = {}
    for b, opts, appr, ex, inf, ids in re.findall(
            r"^\| \`(\w+)\` \| (\d+) \| (\d+) \| (\d+) \| (\d+) \| (.+)$", md, re.M):
        out[b] = {"options": int(opts), "approved": int(appr),
                  "explicit_deny": int(ex), "inferred_deny": int(inf),
                  "ids": re.findall(r"\`([^\`]+)\`", ids)}
    return out

def main():
    picks = {k.split("-", 1)[1]: v for k, v in json.load(open(G / "picks.json"))["beats"].items()}
    beats = {b["id"]: b for v in json.load(open(P / "beats-all.json")).values() for b in v}
    rag = rag_ledger()
    pools = {k: json.load(open(v)) for k, v in POOLS.items() if pathlib.Path(v).exists()}

    gram_fail = {k for k, v in picks.items() if not v["selected"]}
    rag_fail = {k for k, v in rag.items() if not v["approved"]}
    both, only_g, only_r = gram_fail & rag_fail, gram_fail - rag_fail, rag_fail - gram_fail

    O = print
    O("# Denied beats — reconciliation\n")
    O("Read-only. Generated by `pipeline/reconcile_denied.py`. Nothing here is a decision.\n")
    O(f"Two independent methods reviewed the same 40 beats: this system's job grammar "
      f"(33/40 served) and a RAG retrieval pilot (32/40 served).\n")
    O(f"- **Failed under BOTH — the library cannot serve these:** "
      f"{', '.join('`'+b+'`' for b in sorted(both))}")
    O(f"- Failed under the grammar only: {', '.join('`'+b+'`' for b in sorted(only_g))}")
    O(f"- Failed under RAG only: {', '.join('`'+b+'`' for b in sorted(only_r))}\n")
    O("A beat one method served and the other did not is a METHOD difference. A beat "
      "both failed is a LIBRARY gap. Only the first kind is fixable by changing how we "
      "select.\n")

    for b in sorted(both) + sorted(only_g) + sorted(only_r):
        beat = beats.get(b, {})
        tag = ("BOTH FAILED" if b in both else
               "grammar failed, RAG served" if b in only_g else "RAG failed, grammar served")
        O(f"\n---\n\n## `{b}` — {tag}\n")
        O(f"**job** `{beat.get('job')}` · **entity_count** {beat.get('entity_count')} "
          f"· **kind** {beat.get('entity_kind') or '—'}\n")
        O(f"> {beat.get('quote','')}\n")
        mp = beat.get("must_be_perceptible") or []
        wl = beat.get("would_be_a_lie") or []
        O("**Required visual operation** — what the viewer must SEE:")
        O("\n".join(f"- {x}" for x in mp) if mp else "- *none stated*")
        O("\n**Forbidden implication** — what it must NOT say:")
        O("\n".join(f"- {x}" for x in wl) if wl else "- *none stated*")

        O("\n**What each binding pool offers**\n")
        O("| pool | bound | families | conditional |")
        O("|---|---:|---:|---:|")
        for name, pool in pools.items():
            rows = pool.get(beat.get("job"), [])
            fams = len({C._family(r["id"]) for r in rows})
            cond = sum(1 for r in rows if r.get("condition"))
            O(f"| {name} | {len(rows)} | {fams} | {cond} |")

        gp = picks.get(b, {})
        rp = rag.get(b, {})
        O(f"\n**What each method showed and what happened**\n")
        O(f"- grammar: {len(gp.get('shown') or [])} shown, "
          f"{len(gp.get('selected') or [])} selected"
          + (f" — flags: {'raw-b-roll ' if gp.get('rawBroll') else ''}"
             f"{'needs-text' if gp.get('needsTextTemplate') else ''}"
             if gp.get('rawBroll') or gp.get('needsTextTemplate') else ""))
        if gp.get("note"): O(f"  - user note: *\"{gp['note']}\"*")
        O(f"- RAG: {rp.get('options',0)} retrieved, {rp.get('approved',0)} approved, "
          f"{rp.get('explicit_deny',0)} explicit deny, {rp.get('inferred_deny',0)} inferred")
        if rp.get("ids"): O(f"  - approved: {', '.join('`'+i+'`' for i in rp['ids'])}")

        live = pools.get("merged (live)", {}).get(beat.get("job"), [])
        conds = [(r["id"], r["condition"]) for r in live if r.get("condition")][:6]
        if conds:
            O(f"\n**Conditions on the live bindings — UNRESOLVED, nothing evaluates these**\n")
            for i, c in conds:
                O(f"- `{i[:44]}` — {c}")
            if len(live) > 6:
                O(f"- *...and {sum(1 for r in live if r.get('condition'))-6} more conditional bindings*")
        O(f"\n**Can the condition be met with supported template controls?** "
          f"UNRESOLVED — requires the user or a versioned prompt, not a reading.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
