"""Candidate builder. Pool = approved-list.json (authoritative), multi-axis capacity, 33% tolerance."""
import json, re, math, collections

def _rj(path):
    """Read JSON and close the handle."""
    with open(path) as f: return json.load(f)
S="/Users/dwaynetoler/Documents/ChatGPT/Polish/ae-template-automation/scene-library"
TOL=1/3.0   # 6 -> 4..8

def bounds(n):
    d=max(1, round(n*TOL))
    return n-d, n+d

def axes(rec):
    """Every capacity axis a record declares, not the first key found."""
    out={}
    cap=rec.get("capacity") or {}
    for k,v in (cap.get("semantic_counts") or {}).items():
        if isinstance(v,(int,float)): out[k]=int(v)
        elif isinstance(v,list) and v and all(isinstance(x,(int,float)) for x in v):
            out[k+"[n]"]=len(v); out[k+"[sum]"]=int(sum(v))
    cr=cap.get("csv_rows") or {}
    if isinstance(cr.get("exact"),int): out["csv_rows"]=cr["exact"]
    fa=(rec.get("selectionContract") or {}).get("focalAssetCount")
    if isinstance(fa,int): out["focalAssetCount"]=fa
    return out

# The approved list, preferring the LOCAL export.
#
# Codex's tree is on a Documents path whose read permission flaps: on 2026-09-21 the
# whole pool went PermissionError mid-session, twice, and C.load() raised so nothing
# downstream could run. The local export at astra-selector-design/approved_media is
# generated by the same pipeline, is newer, and carries `description` inline on all
# 375 scenes — so it does not need description-inventory.json at all.
LOCAL_APPROVED = "/Users/dwaynetoler/timeline/astra-selector-design/approved_media/approved-list.json"
APPROVED = S + "/approved/approved-list.json"

def approved_path():
    import os
    return LOCAL_APPROVED if os.path.exists(LOCAL_APPROVED) else APPROVED

def _optional(path, default):
    """Enrichment, not a dependency.

    description-inventory.json and catalog.json ENRICH the pool; the approved list is
    authoritative. Until 2026-09-21 both were hard requirements, so an unreadable
    enrichment file took down the entire pool. That is a dependency inversion: the
    optional source could veto the authoritative one.

    Returns (data, why-it-is-missing). NEVER silent — the reason is recorded on every
    record's `sources`, so a thin record is visibly thin rather than mysteriously so.
    """
    try:
        return _rj(path), None
    except (PermissionError, FileNotFoundError) as e:
        return default, f"{type(e).__name__}: {path.split('/')[-1]}"
# Templates whose use is restricted to one content class. Hard filter, applied before
# job matching. See grammar/SCOPE.md.
SCOPED = {
 "archive3-grunge-lyric-video-template": "lyrics",
 "archive3-horizontal-music-players-with-lyric-vol-2": "lyrics",
 "archive3-search-bar-business-timeline-2026-09-12-21-38-59-utc": "timelines",
}

def approved_ids():
    """Every scene and template id in the authoritative approved list."""
    ids=set()
    for c in _rj(APPROVED)["items"]:
        if c.get("templateId"): ids.add(c["templateId"])
        for sc in (c.get("scenes") or []): ids.add(sc["id"])
    return ids

def scope_of(rec_id, template_id=None):
    """Return the content class this record is restricted to, or None."""
    for t, cls in SCOPED.items():
        if rec_id == t or rec_id.startswith(t) or template_id == t:
            return cls
    return None

def load(content_class=None):
    """Pool from approved-list.json (authoritative), enriched with description-inventory
    and the catalog's structured fields. content_class admits scoped templates."""
    inv_raw, inv_why = _optional(S+"/description-inventory.json", {"entries": []})
    inv={e["id"]:e for e in inv_raw["entries"]}
    cat, cat_why = _optional(S+"/approved/catalog.json",
                             {"afterEffects": [], "infographics": [], "cinematic3d": []})
    detail={}
    for t in cat["afterEffects"]:
        for sc in (t.get("scenes") or []):
            detail[sc["id"]]=dict(sc, _template=t.get("templateId"), _kind="after_effects")
    for r in cat["infographics"]:
        detail[r["template_id"]]=dict(r,_template=r.get("number"),_kind="infographic")
    for r in cat["cinematic3d"]:
        detail[r.get("layout_id")]=dict(r,_template=r.get("number"),_kind="cinematic_3d")

    cap=_capability()
    recs=[]
    for card in _rj(approved_path())["items"]:
        tid=card.get("templateId")
        kind=card.get("type")
        if kind == "asset_retrieval":
            continue
        # the record says whether it may be selected; believe it
        # A user override lifts either gate. The four cinematic_3d layouts were held
        # at selectorEligible=false AND reference_only_pending_feedback_calibration,
        # so they had never once been candidates. The user gave the calibration
        # feedback the status was waiting on and said they MUST be admitted.
        # Overrides live in their own file, dated and attributed — approved-list is a
        # generated export and is never edited by hand.
        admitted = tid in eligibility_overrides()
        if card.get("selectorEligible") is False and not admitted:
            continue
        if str(card.get("catalogStatus") or "").startswith("reference_only") and not admitted:
            continue
        # A card with no scenes IS the record — every cinematic_3d and the layered
        # scene are shaped this way. Synthesizing a scene with only id+title threw
        # away everything that makes them selectable: all ten came out on
        # title-fallback at 27-59 characters, and PROMPT-bind judges the
        # DESCRIPTION. `visualEncoding` alone is 147-596 characters of precise
        # encoding text — "Depth encodes evenly spaced rank order and is not
        # magnitude" — which is exactly what the judgment needs and better than
        # anything written for the after_effects records.
        scenes = card.get("scenes") or [{
            "id": tid, "title": card.get("title"),
            "description": card.get("description") or card.get("visualEncoding"),
            "useWhen": "; ".join((card.get("selection") or {}).get("use_when") or [])
                       or "; ".join(card.get("intents") or []) or None,
            "avoidWhen": card.get("avoidWhen"),
            # `video` is the clip these cards name; `preview` is a still. The five
            # truth-* scenes carry both, the four calibrated layouts only a still.
            "sourcePath": card.get("video") or None,
            "_card": card}]
        for sc in scenes:
            rid=sc.get("id") or tid
            # "*" loads EVERY scoped template, each keeping its `scope` field, so a
            # caller can admit them per beat instead of per run. Until 2026-09-21 the
            # only key was content_class, and nothing in the pipeline ever passed one
            # — shotlist, bind and build_review all call load() bare. A hard filter
            # whose key is never turned is not a restriction, it is a deletion.
            if content_class != "*" and scope_of(rid, tid) not in (None, content_class):
                continue
            e=inv.get(rid, {})
            d=detail.get(rid, {})
            def pick(*cands):
                """Return (value, which source supplied it)."""
                for src, v in cands:
                    if v not in (None, "", [], {}): return v, src
                return None, None
            desc, desc_src = pick(("approved-list", sc.get("description")),
                                  ("inventory",     e.get("description")),
                                  ("catalog",       d.get("description")),
                                  ("title-fallback", sc.get("title")))
            avoid, avoid_src = pick(("approved-list", sc.get("avoidWhen")),
                                    ("catalog-contract", (d.get("selectionContract") or {}).get("avoidWhen")),
                                    ("catalog", d.get("avoid_when")))
            cp=cap.get(rid)
            ax=axes(d)
            if cp:
                # The pass watched the clip and counted what is on screen. That
                # SUPERSEDES focalAssetCount, which counts what is emphasised — a
                # different quantity. scene-005 declares focalAssetCount 1 (one card
                # spotlighted) while four are present; keeping both would make it
                # feasible for a 1-entity beat AND a 4-entity beat, which is the
                # any-axis defect of LOG 0013 in a new form.
                slots={f:cp[f] for f in ("slots_at_once","slots_total")
                       if isinstance(cp.get(f), int) and cp[f] > 0}
                if slots:
                    ax={k:v for k,v in ax.items() if _axis_base(k)!="focalAssetCount"}
                    ax.update(slots)
            _c = sc.get("_card") or {}
            recs.append(dict(
                id=rid, template=tid, kind=kind,
                scope=scope_of(rid, tid),
                isNew=bool(card.get("isNew")),
                description=desc,
                title=sc.get("title"),
                sources={"description": desc_src, "avoid": avoid_src,
                         "enrichmentMissing": [w for w in (inv_why, cat_why) if w] or None},
                useWhen=sc.get("useWhen"),
                axes=ax,
                capability=cp,
                # The MEASURED clip wins. `sourcePath` is the vendor's whole demo
                # reel, and for 3 Archive 3 records it was the pool's clip: a
                # 29s/52s/45s reel standing in for a 3s/10s/4s scene. A review UI
                # would have played the reel, and handoff 025 shipped those reel
                # paths to Codex, who caught it before spending. Where a capability
                # record exists, clip_path is the clip that was actually watched and
                # is the one the record describes. 66 of 375 differ.
                clip=((cap.get(rid) or {}).get("clip_path")
                      or e.get("clip") or (e.get("evidence") or {}).get("clip")
                      or sc.get("sourcePath")),
                narration=((d.get("selectionContract") or {}).get("appropriateNarration")
                           or d.get("intents") or _c.get("intents") or []),
                avoid=avoid or [],
                caveats=(d.get("caveats") or _c.get("caveats") or []),
                encoding=(d.get("visual_encoding") or d.get("function")
                          or _c.get("visualEncoding"))))
    recs.extend(_local(cap, content_class))
    # A clip supplied for a record already in the approved list. Distinct from a
    # local TEMPLATE: attaching a clip does not create a record and must not put an
    # approved one into local_pending(). The card for base-single-billboard carries
    # only a PNG, so without this the video pass can never see it.
    ovr = _clip_overrides()
    cap_ovr = _capacity_overrides()
    for r in recs:
        o = ovr.get(r["id"])
        if o: r["clip"] = o["clip"]
        # Subject capacity the user declared for a record whose card states it only
        # in prose — "1-3 heroes", "five-entity CSV row". Unparseable without a
        # judgment, so the user makes it.
        co = cap_ovr.get(r["id"])
        if co:
            # REPLACES the measured slot axes, does not sit beside them. The video
            # pass saw ONE render — for the hero it read slots_at_once 4 / total 6,
            # while the user declares 3 heroes and 10 entities from the layer
            # contract. Both in the same dict is incoherent data that happens to
            # give the right band by max(). Same logic as FACTS 2.9: a measurement
            # observes one instance, the declaration describes the template.
            keep = {k: v for k, v in (r.get("axes") or {}).items()
                    if k not in ("slots_at_once", "slots_total")}
            r["axes"] = {**keep, **(co.get("axes") or {})}
    # A local record may SUPERSEDE one in the approved list. The list is in Codex's
    # tree and this side never writes it, so when the user says "only the clips I
    # asked for should be registered" the only honest route is to register theirs
    # here and remove the one it replaces. The superseded id is named on the record,
    # so this is never a silent deletion.
    # Read from the SIDECAR FILE, not from `recs`. An unmeasured local record is
    # held out of the pool as pending (LOG 0049), so taking supersedes from the
    # loaded records would leave the superseded clip selectable until its
    # replacement was measured — exactly the clip the user said to stop registering.
    # The removal is the user's instruction and does not wait on a measurement.
    # A beat left with nothing is a finding, which is the standing rule.
    recs = [r for r in recs if r["id"] not in _superseded()
            and r["id"] not in _removed()]
    # AFTER the removals, so a correction for a record the user later took out
    # raises instead of being silently skipped.
    return apply_profile_corrections(recs, _profile_corrections())

def _removed():
    """Records the user has taken OUT of the corpus outright.

    Distinct from `supersedes`, which swaps one record for another. These have no
    replacement: the user narrowed the text corpus to exactly what they want and
    said "nothing else". approved-list.json is a generated export and is never
    edited by hand, so the removal lives here with their words.
    """
    import os
    if not os.path.exists(LOCAL): return set()
    return set(_rj(LOCAL).get("remove") or {})

_OVR = None
def eligibility_overrides():
    """Template ids the user has explicitly admitted past a list gate."""
    global _OVR
    if _OVR is None:
        import os
        f = "/Users/dwaynetoler/timeline/grammar/eligibility-overrides.json"
        _OVR = (_rj(f).get("admit") or {}) if os.path.exists(f) else {}
    return _OVR

def _capacity_overrides():
    import os
    if not os.path.exists(LOCAL): return {}
    return _rj(LOCAL).get("capacityOverrides") or {}

def _clip_overrides():
    import os
    if not os.path.exists(LOCAL): return {}
    return _rj(LOCAL).get("clipOverrides") or {}

PROFILE_FIELDS = ("description", "encoding", "useWhen", "avoid", "caveats", "narration")

def _profile_corrections():
    """User corrections to the PROSE a card ships with.

    Distinct from every other override here. clipOverrides fixes a path,
    capacityOverrides an axis, capabilityCorrections a MEASURED record. None of
    them reach the fields PROMPT-bind actually judges: description, encoding,
    useWhen, avoid. A card whose prose is wrong is unfixable without this, and a
    wrong card ships that error into every binding it is ever considered for.

    approved-list.json is a generated export and is never edited by hand, so the
    correction lives here with the user's words, dated and attributed.
    """
    import os
    if not os.path.exists(LOCAL): return {}
    return _rj(LOCAL).get("profileCorrections") or {}

def apply_profile_corrections(recs, corr):
    """Apply `corr` to `recs` in place. Raises rather than failing quietly.

    A correction naming a record that is not in the pool, or a field the judgment
    never reads, is a mistake in the sidecar — a misspelled id, or a record later
    removed. Silence there is the recurring failure mode: the correction sits in
    the file looking applied and the wrong prose keeps shipping.
    """
    by_id = {r["id"]: r for r in recs}
    unknown = [k for k in corr if k not in by_id]
    if unknown:
        raise KeyError(f"profileCorrections names {len(unknown)} record(s) not in "
                       f"the pool: {', '.join(sorted(unknown))}")
    for rid, c in corr.items():
        bad = [f for f in c if not f.startswith("_") and f not in PROFILE_FIELDS]
        if bad:
            raise ValueError(f"profileCorrections[{rid}] sets {bad}; only "
                             f"{list(PROFILE_FIELDS)} are read by the judgment")
        for f in PROFILE_FIELDS:
            if f in c:
                by_id[rid][f] = c[f]
        by_id[rid].setdefault("sources", {})["profile"] = "user-correction"
    return recs

def _superseded():
    import os
    if not os.path.exists(LOCAL): return set()
    return {s for s in ((r.get("provenance") or {}).get("supersedes")
                        for r in (_rj(LOCAL).get("records") or [])) if s}

LOCAL = "/Users/dwaynetoler/timeline/grammar/local-templates.json"

def _local(cap, content_class=None):
    """Templates that live on THIS side of the tree.

    approved-list.json is in Codex's tree and this side never writes it, so a template
    the user drops into ~/timeline/templates has no route into the pool at all. Same
    sidecar pattern capability.json already uses, for the same reason.

    A local record carries NO description and NO axes until a capability pass has
    watched its clip. A description written from a contact sheet is not evidence, and
    an unmeasured record must look unmeasured — `capability: None` is how the rest of
    the pipeline already says "nobody has asked".
    """
    import os
    if not os.path.exists(LOCAL): return []
    doc = _rj(LOCAL)
    out = []
    for r in doc.get("records") or []:
        rid = r["id"]
        # "*" admits every scope, exactly as the approved-list loop does. Without
        # it a LOCALLY registered scoped record could never load by any route — the
        # two timeline scenes were measured, in the sidecar, and invisible to
        # load(), load("timelines") and load("*") alike. The same gate-with-no-key
        # defect as LOG 0057, in the code path that fix did not touch.
        if content_class != "*" and \
           scope_of(rid, r.get("template")) not in (None, content_class): continue
        cp = cap.get(rid)
        # UNMEASURED means PENDING, not present. A record with no capability record
        # has no description either — Claude is not allowed to write one from a
        # contact sheet — and a record with no description cannot be judged by
        # PROMPT-bind, so admitting it would put an unjudgeable card in a slate.
        # local_pending() lists them so "not yet measured" never looks like "not there".
        if not cp: continue
        ax = {f: cp[f] for f in ("slots_at_once", "slots_total")
              if isinstance(cp.get(f), int) and cp[f] > 0}
        out.append(dict(
            id=rid, template=r.get("template"), kind=r.get("kind"),
            scope=scope_of(rid, r.get("template")), isNew=True,
            description=r.get("description") or cp.get("asserts"),
            title=r.get("title"),
            sources={"description": "local-templates", "avoid": None},
            useWhen=None, axes=ax, capability=cp, clip=r.get("clip"),
            narration=[], avoid=[], caveats=[],
            encoding=None, local=True, provenance=r.get("provenance")))
    return out

# ---------------------------------------------------------------------------
# Which axes are a SUBJECT count
#
# A record's capacity block mixes two unrelated kinds of number: how many distinct
# things the scene is ABOUT, and everything else — how many measures each thing has,
# how many rows the data file holds, how many columns the layout uses.
#
# Only the first kind answers "can this scene hold the N things this beat names".
# Treating any number in the block as a capacity let a 15-entity grid clear a
# 1-entity beat on `metrics: 1`. Measured 2026-09-20: 22% of all feasible matches
# qualified on an axis that was not a subject count. See no-drifting LOG 0013.
#
# Both lists are explicit. An axis name in neither raises, rather than defaulting —
# a silent default is how this happened the first time.
# ---------------------------------------------------------------------------
PICKS = "/Users/dwaynetoler/timeline/grammar/picks.json"

def _picked_ids():
    """Every record the user has ever selected. Their pick outranks any tiebreak we
    could write: within a family, a scene they already chose wins the slot."""
    import os
    if not os.path.exists(PICKS): return frozenset()
    return frozenset(i for b in _rj(PICKS)["beats"].values() for i in b.get("selected") or [])

CAPABILITY = "/Users/dwaynetoler/timeline/grammar/capability.json"

def _capability_corrections():
    """User corrections applied on top of a measured capability record.

    They live in local-templates.json, NOT capability.json, so a re-ingest cannot
    quietly drop them. ADD-ONLY: a correction adds what the user saw and never
    removes what the pass measured, so the two stay distinguishable and a later
    re-run under a newer prompt makes the correction reviewable rather than
    permanent.
    """
    import os
    if not os.path.exists(LOCAL): return {}
    return _rj(LOCAL).get("capabilityCorrections") or {}

def _capability():
    """Capability records from the video-understanding pass, keyed by id. A sidecar in
    this tree: approved-list.json lives in Codex's tree and this side never writes it.
    Absent file means the pass has not run."""
    import os
    if not os.path.exists(CAPABILITY): return {}
    cap = _rj(CAPABILITY)
    return apply_capability_corrections(cap, _capability_corrections())


def apply_capability_corrections(cap, corr):
    """`add` unions a list field. `set` replaces a SCALAR one.

    add-only could not express media_slots 0 -> 93. The four marker-plotting
    spatials measured 0 because the demo render showed bare markers; the two that
    already carried portraits measured media_slots == slots_at_once exactly, so
    the zeros are a property of the render and not the template (LOG 0086).

    `set` is deliberately a separate key and refuses list fields. An `add` can
    never delete a measurement; a `set` is an explicit scalar override the user
    has stated, and it stays out of capability.json so a re-ingest cannot bury
    it and a re-measure makes it reviewable.
    """
    for rid, c in corr.items():
        rec = cap.get(rid)
        for field, vals in (c.get("add") or {}).items():
            if rec is None: continue
            rec[field] = sorted(set(rec.get(field) or []) | set(vals))
        for field, val in (c.get("set") or {}).items():
            if isinstance(val, (list, tuple, set, dict)):
                raise ValueError(f"capabilityCorrections[{rid}].set.{field} is a "
                                 f"collection; `set` replaces scalars only, use `add`")
            if rec is None: continue
            rec[field] = val
        if rec is not None and c.get("why"):
            rec["userCorrected"] = c["why"]
    return cap

SUBJECT_AXES = frozenset({
    # how many distinct things are on screen
    "focalAssetCount", "subjects", "entities", "entries", "heroes", "points",
    "periods", "panels", "stages", "quote_blocks", "candidates", "packages",
    "cards", "figures", "pairs",
    # collections, where [n] is how many groups and [sum] how many members
    "group_sizes", "table_sizes", "column_sizes", "tier_sizes", "member_sizes",
    "list_sizes", "ensemble_sizes", "display_column_sizes", "resource_line_sizes",
    # things singled out, which occupy a subject slot
    "named_callouts", "callouts", "peer_callouts", "visible_header_portraits",
    "labeled_data_figures", "context_figures", "summary_rows", "resource_lines",
    # from the capability pass: how many distinct subjects are on screen at once,
    # and how many pass through in total. Both are subject counts.
    "slots_at_once", "slots_total",
})
NON_SUBJECT_AXES = frozenset({
    # attributes OF a subject, not a count of subjects
    "metrics", "variables", "charted_metrics", "plotted_metrics", "paired_metrics",
    "rank_fields", "metric_rank_pairs", "computed_averages", "conditions",
    "stamps_per_subject", "numeric_fields_per_entity", "values_per_pair",
    "scores_per_candidate", "observations_per_panel", "series_per_panel",
    "existing_max_leaders_per_period",
    # data plumbing and layout, not content
    "csv_rows", "display_rows", "display_columns", "hero_media_treatments",
    # labels, which annotate subjects rather than being subjects
    "shared_labels", "status_labels", "criteria_captions",
})

# ---------------------------------------------------------------------------
# Spatial scenes
#
# A 3D spatial scene places markers in a field; the field takes as many as the data
# has. Its capacity is not a property of the template, so declaring a number for it
# would be a fiction. User ruling 2026-09-20: "all spatial scenes have unlimited
# capacity. we can make it whatever we need to."
#
# Above SPATIAL_MAX_SLOTS no flat template is credible, so a beat that big routes to
# a spatial scene and is flagged — the library may simply not hold what it needs.
# ---------------------------------------------------------------------------
SPATIAL_KINDS    = frozenset({"cinematic_3d"})
SPATIAL_MAX_SLOTS = 20
LONG_CAROUSEL_MIN_PEOPLE = 10

# ---------------------------------------------------------------------------
# Match-cut capability
#
# A match cut is many sourced shots shown in turn: festival footage, article
# headlines, a wall of portraits. It is not a separate treatment TYPE — the vessels
# are already in the library. They share one measured signature, derived from the
# capability pass rather than from a family name:
#
#   carries only identity   they show WHAT a thing is, nothing measured
#   many media wells        enough to hold a sequence of sourced clips
#   shown in turn           a sequence, list or grid rather than a single card
#
# Confirmed against the three families the user named for beat 30a, and against
# their picks: 8 shown, 6 selected, 75% acceptance against 30% overall. See
# no-drifting LOG 0030.
# ---------------------------------------------------------------------------
MATCH_CUT_MIN_MEDIA = 6

def is_match_cut(rec, pool_index=None):
    """True when a record can carry a sequence of sourced footage. Requires a
    capability record; a template that has never been measured is never claimed."""
    r = (pool_index or {}).get(rec.get("id")) or rec
    c = r.get("capability")
    if not c: return False
    return (c.get("carries") == ["identity"]
            and (c.get("media_slots") or 0) >= MATCH_CUT_MIN_MEDIA
            and c.get("staging") in ("reveals_in_turn", "all_at_once")
            and c.get("structure") in ("sequence", "list", "grid", "grouped_clusters"))

def match_cut_pool(pool_index):
    return [r for r in pool_index.values() if is_match_cut(r)]

def has_motion(rec, pool_index=None):
    """True when this record has a clip a reviewer can actually watch.

    A still hides the thing being judged — motion is most of what a treatment IS, and
    the user made that a standing rule. 40% of the live slate is stills, all of them
    infographics that have never been rendered. Rendering them is a separate stage and
    not this system's job, so the least this system can do is stop a still taking a
    slot from something watchable when both are otherwise equal.

    This RANKS, it never excludes: a still is often the right answer and the
    infographics are the data-capable half of the library.
    """
    r = (pool_index or {}).get(rec.get("id")) or rec
    c = r.get("clip")
    if c: return True
    # A SPATIAL SCENE IS ALWAYS MOTION, whatever its preview happens to be.
    # User 2026-09-21: "spatial scenes should be treated like video een though its
    # just png for some". Four of the nine ship only a PNG, and that is a fact about
    # the preview, not about the template — the camera is controllable and the point
    # count is unbounded (TEMPLATE-FACTS 2.9). Ranking them last as stills would
    # penalise the nine records least like a still in the whole corpus, and they are
    # the only ones carrying the relations the library is shortest of.
    if r.get("kind") in SPATIAL_KINDS: return True
    import os
    for base in ("/Users/dwaynetoler/Documents/ChatGPT/Polish/infographic-template-system/output",
                 "/Users/dwaynetoler/Documents/ChatGPT/Polish/ae-template-automation"
                 "/scene-library/approved/previews/cinematic-3d"):
        for ext in (".mp4", "-v2.mp4"):
            if os.path.exists(os.path.join(base, r.get("id", "") + ext)): return True
    return False

def is_spatial(rec):
    return rec.get("kind") in SPATIAL_KINDS

def needs_spatial(entity_count):
    """True when no flat template can credibly hold this many things."""
    return isinstance(entity_count, int) and entity_count > SPATIAL_MAX_SLOTS

def needs_long_carousel(entity_count):
    """True when a people roster should expose a capacity-qualified AE carousel."""
    return isinstance(entity_count, int) and entity_count >= LONG_CAROUSEL_MIN_PEOPLE

def is_long_media_carousel(rec, required_slots=LONG_CAROUSEL_MIN_PEOPLE):
    """Return whether an AE media carousel is measured to hold the full roster.

    The distinction is intentionally structural. A title containing ``carousel`` is
    not enough: the record must be an After Effects template, carry identity through
    media, reveal a sequence in turn, and report enough media and total slots. This
    excludes text-list carousels as well as spatial and infographic-system scenes.
    """
    if rec.get("kind") != "after_effects":
        return False
    if not isinstance(required_slots, int) or required_slots < LONG_CAROUSEL_MIN_PEOPLE:
        return False
    label = " ".join(str(rec.get(key) or "") for key in ("id", "template", "title")).lower()
    if "carousel" not in label:
        return False
    capability = rec.get("capability") or {}
    if capability.get("structure") != "sequence" or capability.get("staging") != "reveals_in_turn":
        return False
    if "identity" not in (capability.get("carries") or []):
        return False
    media_slots = capability.get("media_slots")
    total_slots = capability.get("slots_total")
    return (
        isinstance(media_slots, int)
        and isinstance(total_slots, int)
        and min(media_slots, total_slots) >= required_slots
    )

def _axis_base(k):
    return k.split("[")[0]

def unclassified_axes(recs):
    """Axis names in neither list. Preflight fails on these rather than guessing."""
    seen = set()
    for r in recs:
        for k in (r.get("axes") or {}):
            b = _axis_base(k)
            if b not in SUBJECT_AXES and b not in NON_SUBJECT_AXES: seen.add(b)
    return sorted(seen)

def subject_axes(rec):
    """Only the axes that count distinct things the scene is about.

    Raises on an unknown axis name. A new template introducing a new name must be
    classified by a human, not defaulted in either direction."""
    out = {}
    for k, v in (rec.get("axes") or {}).items():
        b = _axis_base(k)
        if b in SUBJECT_AXES:       out[k] = v
        elif b in NON_SUBJECT_AXES: continue
        else: raise ValueError(
            f"unclassified capacity axis {b!r} on {rec.get('id')!r} — add it to "
            f"SUBJECT_AXES or NON_SUBJECT_AXES in candidates.py, do not default it")
    return out

FEASIBLE = frozenset({"exact", "within", "unknown", "unlimited"})

def shape(recs, n):
    lo,hi=bounds(n); out=[]
    for r in recs:
        if is_spatial(r):
            out.append((r,"unlimited",[("unlimited",n)])); continue
        ax=subject_axes(r)
        hits=[(k,v) for k,v in ax.items() if lo<=v<=hi]
        if hits:
            exact=any(v==n for _,v in hits)
            out.append((r,"exact" if exact else "within", hits))
        elif not ax:
            # no SUBJECT axis declared. A record may declare metrics and csv_rows and
            # still say nothing about how many things it holds; that is unknown, not
            # outside. Missing capacity never disqualifies.
            out.append((r,"unknown",[]))
        else:
            out.append((r,"outside", sorted(ax.items(), key=lambda kv:abs(kv[1]-n))[:2]))
    return out


# Suffix shapes observed in the pool: --scene-N, --review-N, --review-vN-N, and those
# with a trailing letter (--review-Nb). A family is the id with that suffix removed.
_FAM_SUFFIX = re.compile(r"--(review|scene)(-v\d+)?-\d+[a-z]?$")

def _family(row):
    return _FAM_SUFFIX.sub("", row if isinstance(row, str) else row.get("id", ""))

def capacity_band(row, pool_index=None):
    """Coarse scale band, for display and audit only. Never disqualifies."""
    rec = (pool_index or {}).get(row.get("id")) or row
    ax = subject_axes(rec)          # not every axis: csv_rows 11 made a 2-subject
    if not ax: return "unknown"     # scene read as "several". See LOG 0013.
    n = max(ax.values())
    if n <= 1:  return "one"
    if n <= 4:  return "few"
    if n <= 12: return "several"
    return "many"

# ---------------------------------------------------------------------------
# Slate diversification
#
# One rule: a slate carries at most FAM_MAX scenes from any one template family.
# Family is the strongest available proxy for design language — two scenes from one
# pack share typography, motion and colour, so twelve of them is one choice wearing
# twelve hats.
#
# Mechanism clustering used to sit here as a second axis. It was removed 2026-09-20
# after measurement: its cap never fired on any job, and disabling it entirely changed
# 12 slate rows across 4 of 20 jobs. It was doing a tiebreak, at the cost of a whole
# subsystem, a review UI and an overrides file. See no-drifting LOG 0016.
# ---------------------------------------------------------------------------
FLOOD_PCT = 40      # over this share of the corpus, a job is not discriminating
FAM_MAX   = 1       # at most this many scenes from one template family in a slate
SLIDE_MAX = 3       # at most this many slideshow-ish entries before the slate must vary

# "We have seen enough slideshows" is taste, and taste is not locked to an exact name.
# These are CONTAINS stems against the template family, deliberately loose: a pack
# called "photo-slideshow-vertical-v3" should read as slide-ish without anyone
# updating a list. Loose matching is safe here because the consequence is only slate
# ORDER — a slide-ish record is never excluded from the pool, just pushed down the
# slate once three of its kind are already shown.
SLIDEISH_STEMS = ("slideshow", "photo", "carousel", "memories", "slides", "gallery")

def is_slideish(row):
    fam = _family(row).lower()
    return any(t in fam for t in SLIDEISH_STEMS)

def _within_family(r, pool_index=None):
    """Order scenes inside one family. Two real signals, then a stable arbitrary
    tiebreak — and the arbitrary part is named as such rather than pretending to rank.

      0a. how well its declared capacity fits the beat, when shotlist annotated it.
          A poor fit is not a defect — slots are re-cuttable (FACTS 2.7) — but a
          template that already holds the right number needs less work.
      0. a record the USER has already selected beats everything — their pick is the
         strongest evidence in the system, and a slate that stops showing what they
         chose is worse than one that does
      1. a binding the model judged `clear` beats one it judged `conditional`
      2. a record that declares a subject capacity beats one we know nothing about
      3. id, so the result is reproducible
    """
    FIT = {"exact": 0, "unlimited": 0, "footage": 0, "within": 1, "unknown": 2, "outside": 3}
    enc = r.get("_encfit", 0)
    fit = FIT.get(r.get("_capfit"), 2)
    # STAGE 2. `_rel` is a relevance score against this beat, set by the retrieval
    # index when one is loaded. Before it existed this slot was `id` — alphabetical —
    # which is the failure diagnosed on day one and never actually removed, only
    # buried under four other keys. Negated so higher similarity sorts first.
    rel = -(r.get("_rel") or 0.0)
    # A watchable clip outranks a still when everything else is equal. Last key before
    # the arbitrary one, so it never overrides fit, a user pick, or relevance.
    still = not has_motion(r, pool_index)
    picked = r["id"] not in _picked_ids()
    clear = ((r.get("provenance") or {}).get("verdict") != "clear")
    rec = (pool_index or {}).get(r.get("id")) or r
    try: declared = not subject_axes(rec)
    except ValueError: declared = True
    return (picked, enc, fit, clear, declared, rel, still, r["id"])

def diversify(rows, limit=12, corpus_size=None, pool_index=None,
              bound_families=None):
    """Return (slate, flooded, note).

    At most FAM_MAX scenes per template family, families visited rarest-first so an
    unusual pack is not crowded out by a large one. A slate shorter than `limit` means
    the library has that few families for this job; it is never padded.
    """
    flooded = corpus_size is not None and len(rows) * 100 / corpus_size > FLOOD_PCT

    fams = collections.defaultdict(list)
    for r in rows: fams[_family(r)].append(r)
    for f in fams: fams[f].sort(key=lambda r: _within_family(r, pool_index))
    # A family holding a record the user has already picked is visited FIRST. Rarest
    # -first is a reasonable default for families nobody has judged; it is not a reason
    # to drop a family the user has endorsed. Measured: on `enumerate` (249 bound, 12
    # families shown) two user-picked families fell outside the cut.
    picked = _picked_ids()
    FIT = {"exact": 0, "unlimited": 0, "footage": 0, "within": 1, "unknown": 2, "outside": 3}
    def bestfit(f): return min(FIT.get(r.get("_capfit"), 2) for r in fams[f])
    # ENCODING FIT OUTRANKS CAPACITY FIT. A slot count is re-cuttable and rendering
    # happens after selection (FACTS 2.6, 2.7, 3.6), so capacity is a hint about
    # scale. Whether a template can make the beat's relation VISIBLE is not
    # adjustable downstream — it is what the template does to data. Ranking scale
    # above meaning is how a slate full of correctly-sized slideshows was offered to
    # a beat that needed an aggregate.
    def bestenc(f): return min(r.get("_encfit", 0) for r in fams[f])
    # STAGE 2, at the level where it decides something. A family's relevance is its
    # BEST member's, because one member is what will represent it. Placed ahead of
    # family size and name: those are diversity heuristics for families nobody has
    # judged, and they were deciding the whole cut. `f` — the family NAME — was the
    # last word until 2026-09-21; that is the alphabetical fallback diagnosed on day
    # one, removed from _within_family and still living here one level up.
    def bestrel(f): return -max((r.get("_rel") or -1.0) for r in fams[f])
    # A family with no watchable clip sorts after one that has a clip, all else equal.
    # It must live HERE, not in _within_family: every still-only record is its own
    # family (46 records, 46 families, zero families with mixed motion), so the
    # within-family comparison never arises. Ranks, never excludes.
    def nomotion(f): return not any(has_motion(r, pool_index) for r in fams[f])
    # A record the USER NAMED FOR THIS BEAT sorts with the families they have
    # picked from, above every ranking signal. Beat 24's note was "the timeline
    # template clips, they absolutely should've been in here" — declaring the
    # content class admitted them and then the 10-slot cut dropped them again, so
    # the declaration achieved nothing. An admission is a statement that this
    # record belongs on this beat; it still competes WITHIN its family and still
    # earns its position among other named records, but it is not outranked by a
    # generic binding.
    NAMED = {"user-named", "scoped"}
    def named(f): return not any((r.get("provenance") or {}).get("verdict") in NAMED
                                 for r in fams[f])
    # NAMED BEATS PICKED, because named is about THIS beat and picked is global.
    # _picked_ids() is every record the user has ever selected anywhere — 61 after
    # pass 1, 103 after pass 2 — so as picks accumulate, "this family contains a
    # picked record" becomes true of most families and stops discriminating. On
    # beat 24 it outranked a timeline the user had explicitly declared for that
    # beat. A global signal must not outrank a beat-specific one.
    order = sorted(fams, key=lambda f: (named(f),
                                        not any(r["id"] in picked for r in fams[f]),
                                        bestenc(f), bestfit(f), bestrel(f),
                                        nomotion(f), len(fams[f]), f))

    slate, slid, deferred = [], 0, []
    for nth in range(FAM_MAX):            # one full pass per allowed scene per family
        for f in order:
            if len(slate) >= limit: break
            if len(fams[f]) <= nth: continue
            r = fams[f][nth]
            # A match-cut vessel is not "another slideshow" — it is its own
            # treatment, and the highest-acceptance one in the library (75% against
            # 30% overall). Carousels match the slide-ish stems, so without this the
            # cap spends its three slots on photo packs and withholds every vessel
            # behind them. Measured on beat 30a: 43 rows in, 4 out, all 17 match-cuts
            # dropped because three history-slideshow families filled the cap first.
            requested = ((r.get("provenance") or {}).get("verdict") == "match-cut"
                         or is_match_cut(r, pool_index))
            if is_slideish(r) and not requested:
                if slid >= SLIDE_MAX: deferred.append(r); continue
                slid += 1
            # THE REST OF THE FAMILY, carried on the chosen scene rather than
            # spending slate slots. FAM_MAX=1 was set after a slate came back 7 scenes
            # from one pack — the cap is right, but it hides 429 bound siblings across
            # 40 beats and the user has twice said "right family, wrong scene" with no
            # way to reach the sibling. Already ranked by _within_family, so [0] is the
            # shown one and the rest are in order.
            r["_siblings"] = [x["id"] for x in fams[f] if x["id"] != r["id"]]
            slate.append(r)
        if len(slate) >= limit: break
    # HARD cap. Past SLIDE_MAX the slate goes SHORT rather than filling with more of
    # the same — a fourth near-identical photo card is not a fourth choice, it is the
    # review time this cap exists to protect. The note says how many were withheld so
    # "short" is never read as "the library is empty".
    withheld = len(deferred)

    note = None
    if flooded or len(slate) < limit or withheld:
        bits = []
        if withheld:
            bits.append(f"{withheld} further slideshow-style scene(s) withheld past the "
                        f"cap of {SLIDE_MAX}; they are more of what is already shown.")
        if flooded:
            bits.append(f"{len(rows)} options, {len(rows)*100//(corpus_size or len(rows))}% "
                        f"of the corpus — this job is not discriminating.")
        bits.append(f"{len(rows)} candidate(s) here across {len(fams)} template "
                    f"families; showing {len(slate)}, at most {FAM_MAX} per family.")
        if len(slate) < limit:
            # REPORT THE OBSERVATION, NOT THE CAUSE. User ruling 2026-09-22: "we are
            # replicating taste and in the early stages, come stuff will not have an
            # answer just yet." LOG 0077.
            #
            # `rows` and `fams` are what reached diversify — AFTER
            # drop_prior_rejections. Counting them and calling the result a fact
            # about the library is how "the library has only 2 families" got printed
            # for a job bound across 8. LOG 0040 fixed the same sentence once by
            # checking len(fams) < limit; the check was right and the input was not.
            #
            # `bound_families` is the count BEFORE any beat-specific removal. Only
            # it can support a claim about the library, and only when nothing was
            # removed. Otherwise the note states what it saw and stops.
            if withheld:
                bits.append(f"Fewer than {limit}: the slideshow cap of {SLIDE_MAX} "
                            f"ended the slate.")
            elif bound_families is not None and bound_families > len(fams):
                bits.append(f"Fewer than {limit}: {bound_families} families are bound "
                            f"to this job, {len(fams)} reached this beat. The "
                            f"difference was removed earlier on this beat, not "
                            f"missing from the library.")
            elif bound_families is not None and bound_families <= limit:
                bits.append(f"Fewer than {limit}: {bound_families} families are bound "
                            f"to this job and all of them reached this beat.")
            else:
                bits.append(f"Fewer than {limit}; {len(fams)} families reached this "
                            f"beat.")
        note = " ".join(bits)
    return slate, flooded, note


def local_pending():
    """Local templates cut and recorded but not yet measured. Not in the pool."""
    import os
    if not os.path.exists(LOCAL): return []
    cap = _capability()
    return [r["id"] for r in (_rj(LOCAL).get("records") or []) if r["id"] not in cap]
